# Pull our base SteamCMD image
FROM thetestgame/steam:stable

# Set our required environment variables
ENV PUID=50510
ENV PGID=50510
ENV UPDATE_SERVER=1
ENV PLATFORM=linux
ENV STEAM_APP_ID=222840

# Expose our ports
EXPOSE 27015
EXPOSE 27015
EXPOSE 27016
EXPOSE 7777
EXPOSE 7778

# Copy our startup script into the container
COPY custom_server /data/custom_server