name: Build and Publish (Eco)
on:
  # Run on every main branch push to the eco folder
  push:
    branches: 
      - main
    paths: 
      - servers/eco/*

  # Run every Tuesday at 1PM UTC (9AM EST)
  schedule:
    - cron: "0 13 * * 2"

jobs:
  # Deploy a new image to Github Packages
  build-and-publish-github-actions:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2.5.0

    - name: Build and publish Docker image to Github Actions (Staging)
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: eco
        image-tag: staging
        build-context: ./servers/eco 
        dockerfile: ./servers/eco/Dockerfile.Staging

    - name: Build and publish Docker image to Github Actions (Latest)
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: eco
        image-tag: latest
        build-context: ./servers/eco 
        dockerfile: ./servers/eco/Dockerfile.Release

    - name: Build and publish Docker image to Github Actions (Release)
      uses: VaultVulp/gp-docker-action@1.5.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        image-name: eco
        image-tag: release
        build-context: ./servers/eco 
        dockerfile: ./servers/eco/Dockerfile.Release

  # Deploy a new image to DockerHub
  build-and-publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0

      # Build Docker Image
      - name: Build Docker Image
        run: |
          cd servers/eco
          docker build . --tag thetestgame/eco:staging --file Dockerfile.Staging
          docker build . --tag thetestgame/eco:latest --file Dockerfile.Release
          docker build . --tag thetestgame/eco:release --file Dockerfile.Release

      # Authenticate with DockerHub prior to publishing
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

        # Publish our built container image
      - name: Push Docker Image
        run: |
          docker push thetestgame/eco:staging
          docker push thetestgame/eco:latest
          docker push thetestgame/eco:release

  # Update our DockerHub README
  docker-hub-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: thetestgame/eco
          readme-filepath: ./servers/eco/README.md